# Generated by Django 3.2 on 2021-05-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='order_id',
            new_name='order',
        ),
    ]
